In [267]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score

In [268]:
data = pd.read_csv("Train.csv")
data = data.drop(columns = ["Unnamed: 0","Name"])

In [269]:
data = data.dropna()
data = data.reset_index()
data.info()
data["Engine"] = data["Engine"].str.replace(" CC"," ").astype(float)
data["Mileage"] = data["Mileage"].str.replace(" kmpl", " ").astype(float)
data["Power"] = data["Power"].str.replace(" bhp", " ")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3717 entries, 0 to 3716
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              3717 non-null   int64
 1   Location           3717 non-null   object
 2   Year               3717 non-null   int64
 3   Kilometers_Driven  3717 non-null   int64
 4   Fuel_Type          3717 non-null   object
 5   Transmission       3717 non-null   object
 6   Owner_Type         3717 non-null   object
 7   Mileage            3717 non-null   object
 8   Engine             3717 non-null   object
 9   Power              3717 non-null   object
 10  Seats              3717 non-null   float64
 11  Price              3717 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 348.6+ KB

In [270]:
data = data[data["Power"]!= "null "]

In [271]:
data["Transmission"] = data["Transmission"].map({"Manual":0,"Automatic": 1})
data["Fuel_Type"] = data["Fuel_Type"].map({"Petrol": 0, "Diesel": 1})
data = pd.get_dummies(data, columns = ["Owner_Type","Location"],dtype = int)
# data = pd.get_dummies(data, columns = [],dtype = int)

In [272]:
data = data.drop(columns = ["index"])

In [273]:
data = data.dropna()
data = data.reset_index()
data = data.astype(float)
data

,index,Year,Kilometers_Driven,Fuel_Type,Transmission,Mileage,Engine,Power,Seats,Price,...,Location_Bangalore,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune
0,0.0,2017.0,16500.0,0.0,0.0,23.84,1199.0,84.00,5.0,5.00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,2017.0,47357.0,1.0,1.0,18.49,1493.0,100.00,7.0,8.37,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2.0,2014.0,35000.0,0.0,0.0,15.00,1598.0,103.52,5.0,4.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,3.0,2007.0,200000.0,1.0,0.0,17.20,1396.0,53.50,5.0,0.85,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,4.0,2013.0,64000.0,1.0,0.0,21.02,1248.0,88.76,5.0,2.65,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,3712.0,2009.0,150000.0,1.0,1.0,11.00,2993.0,235.00,5.0,18.75,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3645,3713.0,2012.0,85000.0,1.0,1.0,11.79,2179.0,120.00,7.0,6.25,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3646,3714.0,2007.0,55100.0,0.0,0.0,18.90,998.0,67.10,5.0,1.45,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3647,3715.0,2014.0,77500.0,1.0,0.0,20.45,1461.0,83.80,5.0,6.60,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3648,3716.0,2012.0,40000.0,0.0,0.0,18.90,998.0,67.10,5.0,2.35,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [274]:
means = data.mean()
stds = data.std()
std_data = (data-means)/stds
std_data

,index,Year,Kilometers_Driven,Fuel_Type,Transmission,Mileage,Engine,Power,Seats,Price,...,Location_Bangalore,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune
0,-1.737993,1.127269,-1.020251,-1.078282,-0.641477,1.316366,-0.711259,-0.546072,-0.351374,-0.411212,...,-0.255702,-0.295436,-0.360604,-0.306801,2.649124,-0.278089,-0.347867,-0.312117,-0.390068,-0.323612
1,-1.737059,1.127269,-0.255071,0.927147,1.558475,0.068488,-0.223363,-0.251070,2.121461,-0.112353,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,-0.278089,2.873875,-0.312117,-0.390068,-0.323612
2,-1.736126,0.176632,-0.561495,-1.078282,-0.641477,-0.745549,-0.049114,-0.186170,-0.351374,-0.455553,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,-0.278089,-0.347867,-0.312117,2.562955,-0.323612
3,-1.735192,-2.041520,3.530111,0.927147,-0.641477,-0.232403,-0.384335,-1.108418,-0.351374,-0.779243,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,3.594988,-0.347867,-0.312117,-0.390068,-0.323612
4,-1.734259,-0.140247,0.157636,0.927147,-0.641477,0.658606,-0.629943,-0.458309,-0.351374,-0.619615,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,-0.278089,-0.347867,-0.312117,2.562955,-0.323612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,1.727338,-1.407762,2.290231,0.927147,1.558475,-1.678542,2.265903,2.238006,-0.351374,0.808168,...,-0.255702,3.383901,-0.360604,-0.306801,-0.377380,-0.278089,-0.347867,-0.312117,-0.390068,-0.323612
3645,1.728272,-0.457125,0.678385,0.927147,1.558475,-1.494276,0.915061,0.117682,2.121461,-0.300359,...,-0.255702,-0.295436,-0.360604,3.258544,-0.377380,-0.278089,-0.347867,-0.312117,-0.390068,-0.323612
3646,1.729205,-2.041520,-0.063063,-1.078282,-0.641477,0.164119,-1.044820,-0.857667,-0.351374,-0.726034,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,-0.278089,-0.347867,-0.312117,-0.390068,-0.323612
3647,1.730139,0.176632,0.492403,0.927147,-0.641477,0.525654,-0.276467,-0.549759,-0.351374,-0.269320,...,-0.255702,-0.295436,-0.360604,-0.306801,2.649124,-0.278089,-0.347867,-0.312117,-0.390068,-0.323612
3648,1.731072,-0.457125,-0.437507,-1.078282,-0.641477,0.164119,-1.044820,-0.857667,-0.351374,-0.646220,...,-0.255702,-0.295436,-0.360604,-0.306801,-0.377380,-0.278089,-0.347867,3.203051,-0.390068,-0.323612

In [275]:
x_train = std_data.drop(columns = ["Price"])
y_train = std_data["Price"]

In [276]:
lr = 0.0001
rows,features = x_train.shape
weight = np.zeros(features)
bias=0
    
for i in range(1000):
    y_pred = np.dot(x_train,weight)+ bias
    db =   np.sum((y_pred - y_train))/(rows)
    dw = np.dot(x_train.T,(y_pred - y_train))
    weight = weight - lr*dw
    bias = bias - lr*db
    cost = np.sum((y_pred - y_train)**2)/(2*rows)
    if i%100 == 0:
        print(cost)

0.49986297615785136
0.14850682878173058
0.1484822709880512
0.14848209354304387
0.14848209226089473
0.14848209225163042
0.14848209225156345
0.14848209225156295
0.148482092251563
0.148482092251563

In [277]:
'''
epoch = 1000
learning_rate = .001
cost_history = []
weight = np.zeros(x_train.shape[1])
intercept = 0
# y_pred = np.dot(x_train,weight) + intercept 
for i in range (epoch):
    y_pred = np.dot(x_train,weight)+ bias
    cost = (1 / (2 * x_train.shape[0])) * np.dot((y_pred - y_train).T,(y_pred-y_train))
    cost_history.append(cost)
    weight -= (learning_rate) * (1/x_train.shape[0]) * np.dot((x_train.T),(y_pred - y_train)) 
    intercept -= (learning_rate) * (1/x_train.shape[0]) * (y_pred - y_train)
    if (i+1) % 100 == 0:
        print(cost)'''

'\nepoch = 1000\nlearning_rate = .001\ncost_history = []\nweight = np.zeros(x_train.shape[1])\nintercept = 0\n# y_pred = np.dot(x_train,weight) + intercept \nfor i in range (epoch):\n    y_pred = np.dot(x_train,weight)+ bias\n    cost = (1 / (2 * x_train.shape[0])) * np.dot((y_pred - y_train).T,(y_pred-y_train))\n    cost_history.append(cost)\n    weight -= (learning_rate) * (1/x_train.shape[0]) * np.dot((x_train.T),(y_pred - y_train)) \n    intercept -= (learning_rate) * (1/x_train.shape[0]) * (y_pred - y_train)\n    if (i+1) % 100 == 0:\n        print(cost)'

In [278]:
r2 = r2_score(y_train, y_pred)
r2

0.7029544108410344